//Exportamos los metodos para seguridad si esta o no logueado...
module.exports = {
    //Si esta logueado...
    isLoggedIn(req, res, next) {
        //Si esta logueado retorne la ruta a la que desea ingresar...
        if(req.isAuthenticated()){
            return next();
        }
        //Si no esta logueado redirija a la ventana de logueo...
        return res.redirect('/signin');
    },

    //Si no esta logueado...
    isNotLoggedIn(req, res, next) {
        //Si NO esta logueado retorne la ruta a la que desea ingresar...
        if(!req.isAuthenticated()){
            return next();
        }
        //Retorne a la venta del perfil...
        return res.redirect('/profile');
    }
};