//importamos el componente timeago...
const { format } = require('timeago.js');

//Creamos un objeto para poder exportar la instancia...
const helpers = {};

//Creamos un metodo del objeto helpers y recibira un objeto...
helpers.timeago = (timestamp)=>{
    //Damos el formato de la fecha y lo retornamos...
    return format(timestamp)
};

//Exportamos el objeto helpers...
module.exports = helpers;