//Instanciamos express...
const express = require('express');
//Instanciamos el modulo router de express...
const router = express.Router();
//Importamos la conexion de BD...
const pool = require('../database');

//Creamos una ruta /add para las peticiones GET, "localhost:4000/softwares/add"...
router.get('/add', (req, res) => {
    //Renderisamos la vista con el siguiente archivo HBS...
    res.render('softwares/add');
});

//Creamos una ruta /add para la peticion POS...
router.post('/add', async (req, res) => {
    /*
    //Muestra por consola la informacion enviada...
    console.log(req.body);
    */
    //Asignamos los campos a guardar en la propiedad req.body...
    const { pro_nom, pro_ver, pro_det, pro_img, pro_url, pro_usu } = req.body;
    //Creamos un objeto para un nuevo programa...
    const newSoftware = {
        pro_nom, 
        pro_ver, 
        pro_det, 
        pro_img, 
        pro_url 
    };
    //Enviamos nuestra informacion a la BD...
    await pool.query('INSERT INTO programas set ?', [newSoftware]);
    /*
    ///Muestra por consola el nuevo objeto...
    console.log(newSoftware);
    //Muestra una respuesta de recibido...
    res.send('Recibido.');
    */
   //Redireccionamos a la ruta de inicio...
   res.redirect('/softwares');
});

//Creamos la ruta /softwares para la peticion GET...
router.get('/', async (req,res)=>{
    //Creamos una constante PROGRAMAS donde se almacenara el query ejecutado...
    const programas = await pool.query('SELECT * FROM programas');
    /*
    //Mostramos el resultado por consola...
    console.log(programas);
    //Enviamos una respuesta...
    res.send('Aca se veran los programas.')
    */
   //Renderisamos la vista con el siguiente archivo HBS, y enviamos los datos... 
   res.render('softwares/list', { programas: programas });
});

//Creamos la ruta /delete para la peticion DELETE...
router.get('/delete/:pro_id',async (req, res)=>{
    /*
    //Mostramos el resultado por consola...
    console.log(req.params.pro_id);
    //Enviamos una respuesta...
    res.send('Programa eliminado...');
    */
    //
});


//Exportamos router...
module.exports = router;