CREATE DATABASE dbs_inventory;
USE dbs_inventory;

CREATE TABLE `usuarios` (
    `usu_id` INT(100) NOT NULL auto_increment PRIMARY KEY,
    `usu_nombres` VARCHAR( 100 ) ,
    `usu_apellidos` VARCHAR( 100 ) ,
    `usu_correo_corporativo` VARCHAR( 100 ) ,
    `usu_correo_personal` VARCHAR( 100 ) ,
    `usu_clave` VARCHAR( 100 ) ,
    `usu_tipo_usuario` VARCHAR( 100 ) ,
    `usu_estado_usuario` VARCHAR( 100 )
);

INSERT INTO `dbs_inventory`.`usuarios` (`usu_id` ,`usu_nombress`, `usu_apellidosllidos` , `usu_correo_corporativo`, `usu_correo_personal`, `usu_clave` , `usu_tipo_usuario` ,`usu_estado_usuario`) 
VALUES ('1', 'Administrador', 'DBS Inventory', 'dbsinventory@db-system.com', 'dbsinventory@db-system.com', '$2a$10$kA7ZMG1JrjX3Od.ZdwzkFuhUSq.spfgrs/RPzrCeLM0RYK2gJe6AG', 'Administrador', 'Activo');

CREATE TABLE `urls_ti` (
    `url_id` INT(100) NOT NULL auto_increment PRIMARY KEY,
    `url_nombre` VARCHAR( 100 ) NOT NULL ,
    `url_url` VARCHAR( 100 ) NOT NULL ,
    `url_detalle` VARCHAR( 100 ) NOT NULL ,
    `url_usuario` VARCHAR( 100 ) NOT NULL ,
    `url_clave` VARCHAR( 100 ) NOT NULL ,
    `url_fecha_actualizacion` timestamp default current_timestamp 
);

CREATE TABLE `software_base` (
    `swb_id` INT(100) NOT NULL auto_increment PRIMARY KEY,
    `swb_nombre` VARCHAR(100),
    `swb_version` VARCHAR(100),
    `swb_detalle` VARCHAR(100),
    `swb_imagen` VARCHAR(100),
    `swb_descarga` VARCHAR(2500),
    `swb_fecha_actualizacion` timestamp default current_timestamp
);

CREATE TABLE `portatiles` (
    `por_id` INT(100) NOT NULL auto_increment PRIMARY KEY,
	`por_id_interno` VARCHAR(100),
	`por_info_estado` VARCHAR(100),
    `por_info_serial` VARCHAR(100),
    `por_info_marca` VARCHAR(100),
    `por_info_modelo` VARCHAR(100),
    `por_info_procesador_modelo` VARCHAR(100),
    `por_info_procesador_velocidad` VARCHAR(100),
    `por_info_procesador_arquitectura` VARCHAR(100),
    `por_info_memoria_tamano` VARCHAR(100),
    `por_info_memoria_referencia` VARCHAR(100),
    `por_info_disco_tamano` VARCHAR(100),
    `por_info_disco_referencia` VARCHAR(100),
    `por_info_mac_ethernet` VARCHAR(100),
    `por_info_mac_wifi` VARCHAR(100),
    `por_info_observaciones` VARCHAR(100),
    `por_info_ruta_imagen` VARCHAR(100),
	`por_sw_sistema_operativo` VARCHAR(100),
    `por_sw_version_so` VARCHAR(100),
    `por_sw_edicion_so` VARCHAR(100),
    `por_sw_product_id` VARCHAR(100),
    `por_sw_product_key` VARCHAR(100),
    `por_sw_ruta_info` VARCHAR(100),
	`por_soporte_remoto_id` VARCHAR(100),
    `por_soporte_remoto_clave` VARCHAR(100),
	`por_adicional_mouse` VARCHAR(100),
    `por_adicional_padmouse` VARCHAR(100),  
    `por_adicional_teclado` VARCHAR(100),    
    `por_adicional_base_refrigerante` VARCHAR(100),    
    `por_adicional_guaya` VARCHAR(100),    
    `por_adicional_clave_guaya` VARCHAR(100),    
    `por_adicional_pantalla` VARCHAR(100),    
    `por_adicional_adaptador_usb_eth` VARCHAR(100),
    `por_adicional_observaciones_dispositivos` VARCHAR(100),
	`por_administrativa_vendedor` VARCHAR(100),
    `por_administrativa_fecha_compra` VARCHAR(100),
    `por_administrativa_costo` VARCHAR(100),
    `por_administrativa_garantia` VARCHAR(100),
	`por_asignacion_consultor` VARCHAR(100),
    `por_asignacion_documento_identidad` VARCHAR(100),
    `por_asignacion_expedicion_documento` VARCHAR(100),
    `por_asignacion_correo_corporativo` VARCHAR(100),
    `por_asignacion_correo_personal` VARCHAR(100),
    `por_asignacion_area` VARCHAR(100),
    `por_asignacion_cargo` VARCHAR(100),
    `por_asignacion_proyecto` VARCHAR(100),
    `por_asignacion_ubicacion` VARCHAR(100),
    `por_asignacion_fecha_asignacion` VARCHAR(100),
    `por_asignacion_observaciones` VARCHAR(100)	
);

CREATE TABLE `escritorio` (
    `esc_id` INT(100) NOT NULL auto_increment PRIMARY KEY,
    `esc_id_interno` VARCHAR(100),
	`esc_info_estado` VARCHAR(100),
    `esc_info_serial` VARCHAR(100),
    `esc_info_marca` VARCHAR(100),
    `esc_info_modelo` VARCHAR(100),
    `esc_info_modelo_procesador` VARCHAR(100),
    `esc_info_velocidad_procesador` VARCHAR(100),
    `esc_info_arquitectura_procesador` VARCHAR(100),
    `esc_info_tamano_memoria` VARCHAR(100),
    `esc_info_memoria_referencia` VARCHAR(100),
    `esc_info_disco_tamano` VARCHAR(100),
    `esc_info_disco_referencia` VARCHAR(100),
    `esc_info_mac_ethernet` VARCHAR(100),
    `esc_info_mac_wifi` VARCHAR(100),
    `esc_info_observaciones` VARCHAR(100),
    `esc_info_ruta_imagen` VARCHAR(100),
	`esc_sw_sistema_operativo` VARCHAR(100),
    `esc_sw_version_so` VARCHAR(100),
    `esc_sw_edicion_so` VARCHAR(100),
    `esc_sw_product_id` VARCHAR(100),
    `esc_sw_product_key` VARCHAR(100),
    `esc_sw_ruta_info` VARCHAR(100),
	`esc_soporte_remoto_id` VARCHAR(100),
    `esc_soporte_remoto_clave` VARCHAR(100),
	`esc_adicional_mouse` VARCHAR(100),
    `esc_adicional_padmouse` VARCHAR(100),  
    `esc_adicional_teclado` VARCHAR(100),    
    `esc_adicional_base_refrigerante` VARCHAR(100),    
    `esc_adicional_guaya` VARCHAR(100),    
    `esc_adicional_clave_guaya` VARCHAR(100),    
    `esc_adicional_pantalla` VARCHAR(100),    
    `esc_adicional_adaptador_usb_eth` VARCHAR(100),
    `esc_adicional_observaciones_dispositivos` VARCHAR(100),
	`esc_administrativa_vendedor` VARCHAR(100),
    `esc_administrativa_fecha_compra` VARCHAR(100),
    `esc_administrativa_costo` VARCHAR(100),
    `esc_administrativa_garantia` VARCHAR(100),
	`esc_asignacion_consultor` VARCHAR(100),
    `esc_asignacion_documento_identidad` VARCHAR(100),
    `esc_asignacion_expedicion_documento` VARCHAR(100),
    `esc_asignacion_correo_corporativo` VARCHAR(100),
    `esc_asignacion_correo_personal` VARCHAR(100),
    `esc_asignacion_area` VARCHAR(100),
    `esc_asignacion_cargo` VARCHAR(100),
    `esc_asignacion_proyecto` VARCHAR(100),
    `esc_asignacion_ubicacion` VARCHAR(100),
    `esc_asignacion_fecha_asignacion` VARCHAR(100),
    `esc_asignacion_observaciones` VARCHAR(100)
);

CREATE TABLE `servidores` (
    `ser_id` INT(100) NOT NULL auto_increment PRIMARY KEY,
    `ser_id_interno` VARCHAR(100),
	`ser_info_estado` VARCHAR(100),
    `ser_info_serial` VARCHAR(100),
    `ser_info_marca` VARCHAR(100),
    `ser_info_modelo` VARCHAR(100),
    `ser_info_modelo_procesador` VARCHAR(100),
    `ser_info_velocidad_procesador` VARCHAR(100),
    `ser_info_arquitectura_procesador` VARCHAR(100),
    `ser_info_tamano_memoria` VARCHAR(100),
    `ser_info_memoria_referencia` VARCHAR(100),
    `ser_info_disco_tamano` VARCHAR(100),
    `ser_info_disco_referencia` VARCHAR(100),
    `ser_info_mac_ethernet` VARCHAR(100),
    `ser_info_mac_wifi` VARCHAR(100),
    `ser_info_observaciones` VARCHAR(100),
    `ser_info_ruta_imagen` VARCHAR(100),
	`ser_sw_sistema_operativo` VARCHAR(100),
    `ser_sw_version_so` VARCHAR(100),
    `ser_sw_edicion_so` VARCHAR(100),
    `ser_sw_product_id` VARCHAR(100),
    `ser_sw_product_key` VARCHAR(100),
    `ser_sw_ruta_info` VARCHAR(100),
	`ser_adicional_mouse` VARCHAR(100),
    `ser_adicional_padmouse` VARCHAR(100),  
    `ser_adicional_teclado` VARCHAR(100),    
    `ser_adicional_base_refrigerante` VARCHAR(100),    
    `ser_adicional_guaya` VARCHAR(100),    
    `ser_adicional_clave_guaya` VARCHAR(100),    
    `ser_adicional_pantalla` VARCHAR(100),    
    `ser_adicional_adaptador_usb_eth` VARCHAR(100),
    `ser_adicional_observaciones_dispositivos` VARCHAR(100),
	`ser_administrativa_vendedor` VARCHAR(100),
    `ser_administrativa_fecha_compra` VARCHAR(100),
    `ser_administrativa_costo` VARCHAR(100),
    `ser_administrativa_garantia` VARCHAR(100),
	`ser_asignacion_consultor` VARCHAR(100),
    `ser_asignacion_documento_identidad` VARCHAR(100),
    `ser_asignacion_expedicion_documento` VARCHAR(100),
    `ser_asignacion_correo_corporativo` VARCHAR(100),
    `ser_asignacion_correo_personal` VARCHAR(100),
    `ser_asignacion_area` VARCHAR(100),
    `ser_asignacion_cargo` VARCHAR(100),
    `ser_asignacion_proyecto` VARCHAR(100),
    `ser_asignacion_ubicacion` VARCHAR(100),
    `ser_asignacion_fecha_asignacion` VARCHAR(100),
    `ser_asignacion_observaciones` VARCHAR(100)
);

CREATE TABLE `impresoras` (
    `imp_id` INT(100) NOT NULL auto_increment PRIMARY KEY,
    `imp_id_interno` VARCHAR(100),
	`imp_info_estado` VARCHAR(100),
    `imp_info_serial` VARCHAR(100),
    `imp_info_marca` VARCHAR(100),
    `imp_info_modelo` VARCHAR(100),
	`imp_administrativa_vendedor` VARCHAR(100),
    `imp_administrativa_fecha_compra` VARCHAR(100),
    `imp_administrativa_costo` VARCHAR(100),
    `imp_administrativa_garantia` VARCHAR(100),
	`imp_asignacion_consultor` VARCHAR(100),
    `imp_asignacion_documento_identidad` VARCHAR(100),
    `imp_asignacion_expedicion_documento` VARCHAR(100),
    `imp_asignacion_correo_corporativo` VARCHAR(100),
    `imp_asignacion_correo_personal` VARCHAR(100),
    `imp_asignacion_area` VARCHAR(100),
    `imp_asignacion_cargo` VARCHAR(100),
    `imp_asignacion_proyecto` VARCHAR(100),
    `imp_asignacion_ubicacion` VARCHAR(100),
    `imp_asignacion_fecha_asignacion` VARCHAR(100),
    `imp_asignacion_observaciones` VARCHAR(100)
);

CREATE TABLE `inventario_software` (
    `isf_id` INT(100) NOT NULL auto_increment PRIMARY KEY,
    `isf_referencia_compra` VARCHAR(100),
    `isf_nombre` VARCHAR(100),
    `isf_version` VARCHAR(100),
    `isf_edicion` VARCHAR(100),
    `isf_product_id` VARCHAR(100),
    `isf_product_key` VARCHAR(100),
    `isf_vendedor` VARCHAR(100),
    `isf_fecha_compra` VARCHAR(100),
    `isf_estado` VARCHAR(100),
    `isf_equipo_asignado` VARCHAR(100)
);