//Inicializaciones...
//Inicializamos express...
const express = require('express');
//Inicializamos morgan...
const morgan = require('morgan');
//Inicializamos las plantllas de express-handlebears...
const exphbs = require('express-handlebars');
//Inicializamos el modulo path de express...
const path = require('path');
const exp = require('constants'); //Generado automaticamente...


//Instanciamientos...
//Ejecutamos express en la constante para la aplicaccion app...
const app = express();


//Configuraciones...
//Asignamos el puerto 4000 para el servidor de express, siempre y cuando no este en uso...
app.set('port', process.env.PORT || 4000);
//Definimos la ruta de la carpeta de vistas... "__dirname obtiene la ruta donde estoy"
app.set('views', path.join(__dirname, 'views'));
//Configuramos las plantillas...
app.engine('.hbs', exphbs({
    //Bombre de la plantilla principal...
    defaultLayout: 'main',
    //Definimos la direccion donde estan las plantillas...
    layoutsDir: path.join(app.get('views'), 'layouts'),
    //Definimos la direccion de partials, esta sera para reutilizar fragmentos de codigo...
    partialsDir: path.join(app.get('views'), 'partials'),
    //Esta propiedad es para definir extenciones que tendran los archivos de handlebars...
    extname: '.hbs',
    //Configuramos la ruta donde se almacenaran las funciones de handlebars...
    helpers: require('./lib/handlebars.js')
}));
//Inicializamos el motor...
app.set('view engine', '.hbs'); 


//Middlewares ()
//Indicamos que nuestra aplicacion usara morgan con el parametro dev, el cual muestra que esta llegando a nuestra aplicacion...
app.use(morgan('dev'));
//Este metodo acepta desde los formularios los datos que envien los usuarios...
app.use(express.urlencoded({extended: false}));
//
app.use(express.json());


//Variables globales...
//Funcion para requerimientos y respuestas
app.use((req, res, next) =>{
    //Esta funcion toma la informacion para continuar...
    next();
});


//Rutas...
//Usamos nuestra ruta inicial...
app.use(require('./routes/index.js'));
//Ruta para la autenticacion del usuario...
app.use(require('./routes/authentication.js'));
//Ruta para el manejo de los links que enviaremos y o recibiremos en el movimiento de la aplicacion...
app.use('/softwares', require('./routes/softwares.js'));


//Archivos publicos...
//Configuramos la ruta de la carpeta public
app.use(express.static(path.join(__dirname, 'public')));

//Inicializacion del servidor...
app.listen(app.get('port'), () => {
    //Mensaje en consola...
    console.log('Corriendo sobre el puerto: ', app.get('port'), '...');
});