//String de conexion de BD...
//Importamos el bojeto de la BD
module.exports = {
    //Nombre del objeto a exportar...
    database: {
        //Hostname o IP del servidor de base de datos...
        host: 'localhost',
        //Nombre de usuario para la conexion de BD...
        user: 'root',
        //Contraseña del usuario de BD...
        password: '',
        //Nombre de la BD...
        database: 'dbs_inventory'
    }
};